language: node_js
node_js:
- '6'
before_install:
- echo "registry = https://realglobe.artifactoryonline.com/realglobe/api/npm/npm-virtual" > $HOME/.npmrc
- curl -u${NPM_USER}:${NPM_PASSWORD} "https://realglobe.artifactoryonline.com/realglobe/api/npm/auth" >> $HOME/.npmrc
- cat $HOME/.npmrc
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
env:
  secure: "GPFIXJIG8fLz6/C1f8+2poS8toxSjHVDmP23PUCT2x9G9WlAptjO4ftB0xWXxSCzm6H+mCuDESafjTkSm5CnlTH+IFfgV2SSFrPlQAuLEzzs/u3U8kfA4DT/E8oLoaJfUQY3Wyf6wxZ71iohpznK0engNItOjYYjOZlb1I0qASXdLao/DwwE4hOQAC4p5OyHSVOBL+stCNOekuiCfLxIzA8ehuBd0yZeBVF/8rVbocBwPzBnZzqcV8s1FfsbwcWgRQOTZNuJECFV2HuWBilU52nGAjN16pq03GZxjHdDiklMyV3yT0TIB2vvvhToxSBlicWLHSbIdbyuXT7q04GSebO2sTr8vIJMLuziJ9DO263gKNFEfniZAFQkgAk4qo7N0vKdWUpQUmtuJIDU76CLp++b4wHst/o/Bc2vO1t8JJtvnivs3B4WpzJawMaXYSd3xJRGdQ2mSjaxSkkKSYyIBPD/KmVZC0YkbUeml7oktmeGMPYHk9EdTt0jhP1pNDhjRt0hRzWfQkWYPUMoGLwUxKjUAbDWZQdcwwBVlUNmtI+Hrxcplw8S61qHbLiq8BFUTh5QG0Eqy4Yl3KuWymE9gG4pd6ayIFxDU2VYpnj90Md3XD9N1H/OdQ4Sgs0f2kNP54EOtY1JUT6/z2lXNrNTWQtB4wc+p4McERun9Q8dty4="